/**
 * Specifies mouse configuration. Speed, available commands
 */
const MOUSE_SPEED_UPPERBOUND = 1000;
const MOUSE_SPEED_LOWERBOUND = 200;
const SCALE_FACTOR_LOWERBOUND = 1;
const SCALE_FACTOR_UPPERBOUND = 10;
const SCALE_FACTOR_Y_LOWERBOUND = 1;
const SCALE_FACTOR_Y_UPPERBOUND = 10;
export {
  MOUSE_SPEED_UPPERBOUND,
  MOUSE_SPEED_LOWERBOUND,
  SCALE_FACTOR_LOWERBOUND,
  SCALE_FACTOR_UPPERBOUND,
  SCALE_FACTOR_Y_LOWERBOUND,
  SCALE_FACTOR_Y_UPPERBOUND,
};
